/** @format */

export let fakeData = [
  {
    _id: "6366833cbeee03bb01e96731",
    title: "Alpaca Cloth Set ",
    desc: "A winning style that's perfect for off-duty days, the Twin Serve epitomises Lacoste's timeless tennis aesthetic. Presented in immaculate leather, its sleek silhouette reimagines the traditional twin-cupsole outline, and elevates it with court-informed perforations and a mesh tongue reminiscent of tennis nets. A contrast heel piece injects an on-brand accent, while urban-influenced outsoles are inspired by varied tennis playing surfaces.",
    variant: [
      {
        img: [
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662571/uz03irgubbqdiemwyfdk.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662578/pqz0hxctdmi51hgzqo1q.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662583/b7jspiodnkaqqhxllpyl.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662585/ir9kjiajs5eirhgbsqko.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662588/miwy9otnqid91qovocgh.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662592/lnsqpvbqx6n3sk845lrs.jpg",
        ],
        color: "red",
        size: ["10", "20", "40"],
        slug: "alpaca-cloth-set",
        price: 500,
        sellPrice: 398,
        availableQty: 100,
        active: false,
        _id: "6366833cbeee03bb01e96732",
      },
    ],
    category: "slipers",
    tag: "Recommended",
    active: false,
    __v: 0,
  },
  {
    _id: "6366833cbeee03bb01e96731",
    title: "Alpaca Cloth Set ",
    desc: "A winning style that's perfect for off-duty days, the Twin Serve epitomises Lacoste's timeless tennis aesthetic. Presented in immaculate leather, its sleek silhouette reimagines the traditional twin-cupsole outline, and elevates it with court-informed perforations and a mesh tongue reminiscent of tennis nets. A contrast heel piece injects an on-brand accent, while urban-influenced outsoles are inspired by varied tennis playing surfaces.",
    variant: [
      {
        img: [
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662571/uz03irgubbqdiemwyfdk.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662578/pqz0hxctdmi51hgzqo1q.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662583/b7jspiodnkaqqhxllpyl.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662585/ir9kjiajs5eirhgbsqko.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662588/miwy9otnqid91qovocgh.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662592/lnsqpvbqx6n3sk845lrs.jpg",
        ],
        color: "red",
        size: ["10", "20", "40"],
        slug: "alpaca-cloth-set",
        price: 500,
        sellPrice: 398,
        availableQty: 100,
        active: false,
        _id: "6366833cbeee03bb01e96732",
      },
    ],
    category: "slipers",
    tag: "Recommended",
    active: false,
    __v: 0,
  },
  {
    _id: "6366833cbeee03bb01e96731",
    title: "Alpaca Cloth Set ",
    desc: "A winning style that's perfect for off-duty days, the Twin Serve epitomises Lacoste's timeless tennis aesthetic. Presented in immaculate leather, its sleek silhouette reimagines the traditional twin-cupsole outline, and elevates it with court-informed perforations and a mesh tongue reminiscent of tennis nets. A contrast heel piece injects an on-brand accent, while urban-influenced outsoles are inspired by varied tennis playing surfaces.",
    variant: [
      {
        img: [
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662571/uz03irgubbqdiemwyfdk.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662578/pqz0hxctdmi51hgzqo1q.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662583/b7jspiodnkaqqhxllpyl.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662585/ir9kjiajs5eirhgbsqko.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662588/miwy9otnqid91qovocgh.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662592/lnsqpvbqx6n3sk845lrs.jpg",
        ],
        color: "red",
        size: ["10", "20", "40"],
        slug: "alpaca-cloth-set",
        price: 500,
        sellPrice: 398,
        availableQty: 100,
        active: false,
        _id: "6366833cbeee03bb01e96732",
      },
    ],
    category: "slipers",
    tag: "Recommended",
    active: false,
    __v: 0,
  },
  {
    _id: "6366833cbeee03bb01e96731",
    title: "Alpaca Cloth Set ",
    desc: "A winning style that's perfect for off-duty days, the Twin Serve epitomises Lacoste's timeless tennis aesthetic. Presented in immaculate leather, its sleek silhouette reimagines the traditional twin-cupsole outline, and elevates it with court-informed perforations and a mesh tongue reminiscent of tennis nets. A contrast heel piece injects an on-brand accent, while urban-influenced outsoles are inspired by varied tennis playing surfaces.",
    variant: [
      {
        img: [
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662571/uz03irgubbqdiemwyfdk.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662578/pqz0hxctdmi51hgzqo1q.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662583/b7jspiodnkaqqhxllpyl.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662585/ir9kjiajs5eirhgbsqko.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662588/miwy9otnqid91qovocgh.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662592/lnsqpvbqx6n3sk845lrs.jpg",
        ],
        color: "red",
        size: ["10", "20", "40"],
        slug: "alpaca-cloth-set",
        price: 500,
        sellPrice: 398,
        availableQty: 100,
        active: false,
        _id: "6366833cbeee03bb01e96732",
      },
    ],
    category: "slipers",
    tag: "Recommended",
    active: false,
    __v: 0,
  },
  {
    _id: "6366833cbeee03bb01e96731",
    title: "Alpaca Cloth Set ",
    desc: "A winning style that's perfect for off-duty days, the Twin Serve epitomises Lacoste's timeless tennis aesthetic. Presented in immaculate leather, its sleek silhouette reimagines the traditional twin-cupsole outline, and elevates it with court-informed perforations and a mesh tongue reminiscent of tennis nets. A contrast heel piece injects an on-brand accent, while urban-influenced outsoles are inspired by varied tennis playing surfaces.",
    variant: [
      {
        img: [
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662571/uz03irgubbqdiemwyfdk.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662578/pqz0hxctdmi51hgzqo1q.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662583/b7jspiodnkaqqhxllpyl.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662585/ir9kjiajs5eirhgbsqko.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662588/miwy9otnqid91qovocgh.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662592/lnsqpvbqx6n3sk845lrs.jpg",
        ],
        color: "red",
        size: ["10", "20", "40"],
        slug: "alpaca-cloth-set",
        price: 500,
        sellPrice: 398,
        availableQty: 100,
        active: false,
        _id: "6366833cbeee03bb01e96732",
      },
    ],
    category: "slipers",
    tag: "Recommended",
    active: false,
    __v: 0,
  },
  {
    _id: "6366833cbeee03bb01e96731",
    title: "Alpaca Cloth Set ",
    desc: "A winning style that's perfect for off-duty days, the Twin Serve epitomises Lacoste's timeless tennis aesthetic. Presented in immaculate leather, its sleek silhouette reimagines the traditional twin-cupsole outline, and elevates it with court-informed perforations and a mesh tongue reminiscent of tennis nets. A contrast heel piece injects an on-brand accent, while urban-influenced outsoles are inspired by varied tennis playing surfaces.",
    variant: [
      {
        img: [
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662571/uz03irgubbqdiemwyfdk.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662578/pqz0hxctdmi51hgzqo1q.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662583/b7jspiodnkaqqhxllpyl.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662585/ir9kjiajs5eirhgbsqko.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662588/miwy9otnqid91qovocgh.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662592/lnsqpvbqx6n3sk845lrs.jpg",
        ],
        color: "red",
        size: ["10", "20", "40"],
        slug: "alpaca-cloth-set",
        price: 500,
        sellPrice: 398,
        availableQty: 100,
        active: false,
        _id: "6366833cbeee03bb01e96732",
      },
    ],
    category: "slipers",
    tag: "Recommended",
    active: false,
    __v: 0,
  },
  {
    _id: "6366833cbeee03bb01e96731",
    title: "Alpaca Cloth Set ",
    desc: "A winning style that's perfect for off-duty days, the Twin Serve epitomises Lacoste's timeless tennis aesthetic. Presented in immaculate leather, its sleek silhouette reimagines the traditional twin-cupsole outline, and elevates it with court-informed perforations and a mesh tongue reminiscent of tennis nets. A contrast heel piece injects an on-brand accent, while urban-influenced outsoles are inspired by varied tennis playing surfaces.",
    variant: [
      {
        img: [
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662571/uz03irgubbqdiemwyfdk.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662578/pqz0hxctdmi51hgzqo1q.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662583/b7jspiodnkaqqhxllpyl.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662585/ir9kjiajs5eirhgbsqko.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662588/miwy9otnqid91qovocgh.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662592/lnsqpvbqx6n3sk845lrs.jpg",
        ],
        color: "red",
        size: ["10", "20", "40"],
        slug: "alpaca-cloth-set",
        price: 500,
        sellPrice: 398,
        availableQty: 100,
        active: false,
        _id: "6366833cbeee03bb01e96732",
      },
    ],
    category: "slipers",
    tag: "Recommended",
    active: false,
    __v: 0,
  },
  {
    _id: "6366833cbeee03bb01e96731",
    title: "Alpaca Cloth Set ",
    desc: "A winning style that's perfect for off-duty days, the Twin Serve epitomises Lacoste's timeless tennis aesthetic. Presented in immaculate leather, its sleek silhouette reimagines the traditional twin-cupsole outline, and elevates it with court-informed perforations and a mesh tongue reminiscent of tennis nets. A contrast heel piece injects an on-brand accent, while urban-influenced outsoles are inspired by varied tennis playing surfaces.",
    variant: [
      {
        img: [
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662571/uz03irgubbqdiemwyfdk.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662578/pqz0hxctdmi51hgzqo1q.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662583/b7jspiodnkaqqhxllpyl.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662585/ir9kjiajs5eirhgbsqko.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662588/miwy9otnqid91qovocgh.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662592/lnsqpvbqx6n3sk845lrs.jpg",
        ],
        color: "red",
        size: ["10", "20", "40"],
        slug: "alpaca-cloth-set",
        price: 500,
        sellPrice: 398,
        availableQty: 100,
        active: false,
        _id: "6366833cbeee03bb01e96732",
      },
    ],
    category: "slipers",
    tag: "Recommended",
    active: false,
    __v: 0,
  },
  {
    _id: "6366833cbeee03bb01e96731",
    title: "Alpaca Cloth Set ",
    desc: "A winning style that's perfect for off-duty days, the Twin Serve epitomises Lacoste's timeless tennis aesthetic. Presented in immaculate leather, its sleek silhouette reimagines the traditional twin-cupsole outline, and elevates it with court-informed perforations and a mesh tongue reminiscent of tennis nets. A contrast heel piece injects an on-brand accent, while urban-influenced outsoles are inspired by varied tennis playing surfaces.",
    variant: [
      {
        img: [
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662571/uz03irgubbqdiemwyfdk.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662578/pqz0hxctdmi51hgzqo1q.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662583/b7jspiodnkaqqhxllpyl.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662585/ir9kjiajs5eirhgbsqko.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662588/miwy9otnqid91qovocgh.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662592/lnsqpvbqx6n3sk845lrs.jpg",
        ],
        color: "red",
        size: ["10", "20", "40"],
        slug: "alpaca-cloth-set",
        price: 500,
        sellPrice: 398,
        availableQty: 100,
        active: false,
        _id: "6366833cbeee03bb01e96732",
      },
    ],
    category: "slipers",
    tag: "Recommended",
    active: false,
    __v: 0,
  },
  {
    _id: "6366833cbeee03bb01e96731",
    title: "Alpaca Cloth Set ",
    desc: "A winning style that's perfect for off-duty days, the Twin Serve epitomises Lacoste's timeless tennis aesthetic. Presented in immaculate leather, its sleek silhouette reimagines the traditional twin-cupsole outline, and elevates it with court-informed perforations and a mesh tongue reminiscent of tennis nets. A contrast heel piece injects an on-brand accent, while urban-influenced outsoles are inspired by varied tennis playing surfaces.",
    variant: [
      {
        img: [
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662571/uz03irgubbqdiemwyfdk.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662578/pqz0hxctdmi51hgzqo1q.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662583/b7jspiodnkaqqhxllpyl.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662585/ir9kjiajs5eirhgbsqko.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662588/miwy9otnqid91qovocgh.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662592/lnsqpvbqx6n3sk845lrs.jpg",
        ],
        color: "red",
        size: ["10", "20", "40"],
        slug: "alpaca-cloth-set",
        price: 500,
        sellPrice: 398,
        availableQty: 100,
        active: false,
        _id: "6366833cbeee03bb01e96732",
      },
    ],
    category: "slipers",
    tag: "Recommended",
    active: false,
    __v: 0,
  },
  {
    _id: "6366833cbeee03bb01e96731",
    title: "Alpaca Cloth Set ",
    desc: "A winning style that's perfect for off-duty days, the Twin Serve epitomises Lacoste's timeless tennis aesthetic. Presented in immaculate leather, its sleek silhouette reimagines the traditional twin-cupsole outline, and elevates it with court-informed perforations and a mesh tongue reminiscent of tennis nets. A contrast heel piece injects an on-brand accent, while urban-influenced outsoles are inspired by varied tennis playing surfaces.",
    variant: [
      {
        img: [
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662571/uz03irgubbqdiemwyfdk.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662578/pqz0hxctdmi51hgzqo1q.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662583/b7jspiodnkaqqhxllpyl.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662585/ir9kjiajs5eirhgbsqko.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662588/miwy9otnqid91qovocgh.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662592/lnsqpvbqx6n3sk845lrs.jpg",
        ],
        color: "red",
        size: ["10", "20", "40"],
        slug: "alpaca-cloth-set",
        price: 500,
        sellPrice: 398,
        availableQty: 100,
        active: false,
        _id: "6366833cbeee03bb01e96732",
      },
    ],
    category: "slipers",
    tag: "Recommended",
    active: false,
    __v: 0,
  },
  {
    _id: "6366833cbeee03bb01e96731",
    title: "Alpaca Cloth Set ",
    desc: "A winning style that's perfect for off-duty days, the Twin Serve epitomises Lacoste's timeless tennis aesthetic. Presented in immaculate leather, its sleek silhouette reimagines the traditional twin-cupsole outline, and elevates it with court-informed perforations and a mesh tongue reminiscent of tennis nets. A contrast heel piece injects an on-brand accent, while urban-influenced outsoles are inspired by varied tennis playing surfaces.",
    variant: [
      {
        img: [
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662571/uz03irgubbqdiemwyfdk.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662578/pqz0hxctdmi51hgzqo1q.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662583/b7jspiodnkaqqhxllpyl.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662585/ir9kjiajs5eirhgbsqko.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662588/miwy9otnqid91qovocgh.jpg",
          "http://res.cloudinary.com/hellooworkd/image/upload/v1667662592/lnsqpvbqx6n3sk845lrs.jpg",
        ],
        color: "red",
        size: ["10", "20", "40"],
        slug: "alpaca-cloth-set",
        price: 500,
        sellPrice: 398,
        availableQty: 100,
        active: false,
        _id: "6366833cbeee03bb01e96732",
      },
    ],
    category: "slipers",
    tag: "Recommended",
    active: false,
    __v: 0,
  },
];
